import type { CronFormatDefinition, CronPreset } from '../types';

export const CRON_FORMATS: CronFormatDefinition[] = [
  {
    id: 'unix',
    label: 'Unix / Linux',
    description: 'Standard 5-field cron used in crontab, systemd timers, and most schedulers',
    placeholder: '* * * * *',
    fields: [
      { name: 'minute', label: 'Minute',     range: '0–59' },
      { name: 'hour',   label: 'Hour',       range: '0–23' },
      { name: 'dom',    label: 'Day (month)', range: '1–31' },
      { name: 'month',  label: 'Month',      range: '1–12' },
      { name: 'dow',    label: 'Day (week)', range: '0–7'  },
    ],
  },
  {
    id: 'quartz',
    label: 'Quartz',
    description: '6-field format used by Quartz Scheduler, Spring @Scheduled, and AWS Lambda',
    placeholder: '0 * * * * *',
    fields: [
      { name: 'second', label: 'Second',     range: '0–59' },
      { name: 'minute', label: 'Minute',     range: '0–59' },
      { name: 'hour',   label: 'Hour',       range: '0–23' },
      { name: 'dom',    label: 'Day (month)', range: '1–31' },
      { name: 'month',  label: 'Month',      range: '1–12' },
      { name: 'dow',    label: 'Day (week)', range: '1–7'  },
    ],
  },
  {
    id: 'github',
    label: 'GitHub Actions',
    description: 'Standard Unix 5-field cron used in GitHub Actions workflow schedule triggers',
    placeholder: '0 0 * * *',
    fields: [
      { name: 'minute', label: 'Minute',     range: '0–59' },
      { name: 'hour',   label: 'Hour',       range: '0–23' },
      { name: 'dom',    label: 'Day (month)', range: '1–31' },
      { name: 'month',  label: 'Month',      range: '1–12' },
      { name: 'dow',    label: 'Day (week)', range: '0–6'  },
    ],
  },
  {
    id: 'aws',
    label: 'AWS EventBridge',
    description: '6-field format for AWS EventBridge (CloudWatch Events) rules',
    placeholder: '0 12 * * ? *',
    fields: [
      { name: 'minute', label: 'Minute',     range: '0–59'      },
      { name: 'hour',   label: 'Hour',       range: '0–23'      },
      { name: 'dom',    label: 'Day (month)', range: '1–31'      },
      { name: 'month',  label: 'Month',      range: '1–12'      },
      { name: 'dow',    label: 'Day (week)', range: '1–7'       },
      { name: 'year',   label: 'Year',       range: '1970–2199' },
    ],
  },
];

export const CRON_PRESETS: CronPreset[] = [
  { label: 'Every minute',         expression: '* * * * *',          format: 'unix',   description: 'Runs every minute' },
  { label: 'Every 5 minutes',      expression: '*/5 * * * *',        format: 'unix',   description: 'Runs every 5 minutes' },
  { label: 'Every 15 minutes',     expression: '*/15 * * * *',       format: 'unix',   description: 'Runs every 15 minutes' },
  { label: 'Every 30 minutes',     expression: '*/30 * * * *',       format: 'unix',   description: 'Runs every 30 minutes' },
  { label: 'Every hour',           expression: '0 * * * *',          format: 'unix',   description: 'Runs at the start of every hour' },
  { label: 'Every 6 hours',        expression: '0 */6 * * *',        format: 'unix',   description: 'Runs at midnight, 06:00, noon, 18:00' },
  { label: 'Every 12 hours',       expression: '0 */12 * * *',       format: 'unix',   description: 'Runs at midnight and noon' },
  { label: 'Daily at midnight',    expression: '0 0 * * *',          format: 'unix',   description: 'Runs once a day at midnight' },
  { label: 'Daily at noon',        expression: '0 12 * * *',         format: 'unix',   description: 'Runs once a day at 12:00' },
  { label: 'Daily at 9 AM',        expression: '0 9 * * *',          format: 'unix',   description: 'Runs once a day at 09:00' },
  { label: 'Weekdays at 9 AM',     expression: '0 9 * * 1-5',        format: 'unix',   description: 'Runs Monday–Friday at 09:00' },
  { label: 'Weekends at noon',     expression: '0 12 * * 6,0',       format: 'unix',   description: 'Runs Saturday and Sunday at 12:00' },
  { label: 'Mon, Wed, Fri 8 AM',   expression: '0 8 * * 1,3,5',      format: 'unix',   description: 'Runs Monday, Wednesday, Friday at 08:00' },
  { label: 'Every Monday 8 AM',    expression: '0 8 * * 1',          format: 'unix',   description: 'Runs every Monday at 08:00' },
  { label: 'Weekly on Sunday',     expression: '0 0 * * 0',          format: 'unix',   description: 'Runs every Sunday at midnight' },
  { label: 'First of month',       expression: '0 0 1 * *',          format: 'unix',   description: 'Runs at midnight on the 1st of each month' },
  { label: 'Last day of month',    expression: '0 0 L * *',          format: 'quartz', description: 'Runs on the last day of every month (Quartz)' },
  { label: 'Every quarter',        expression: '0 0 1 1,4,7,10 *',   format: 'unix',   description: 'Runs on 1st Jan, Apr, Jul, Oct' },
  { label: 'Twice daily',          expression: '0 8,20 * * *',       format: 'unix',   description: 'Runs at 08:00 and 20:00 every day' },
  { label: 'Yearly (Jan 1st)',     expression: '0 0 1 1 *',          format: 'unix',   description: 'Runs at midnight on 1st January' },
  { label: 'GitHub Actions nightly', expression: '0 2 * * *',        format: 'github', description: 'CI nightly build at 02:00 UTC' },
  { label: 'AWS: business hours',  expression: '0 8-18 ? * MON-FRI *', format: 'aws',  description: 'Every hour, Mon–Fri 08:00–18:00' },
];

export const TIMEZONES: string[] = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Asia/Kolkata',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Australia/Sydney',
];
