import type { CronFormatDefinition, CronPreset } from '../types';

export const CRON_FORMATS: CronFormatDefinition[] = [
  {
    id: 'unix',
    label: 'Unix / Linux',
    description: 'Standard 5-field cron used in crontab, systemd timers, most schedulers',
    fieldCount: 5,
    placeholder: '* * * * *',
    example: '0 9 * * 1-5',
    fields: [
      { name: 'minute',  label: 'Minute',      range: '0–59',    special: ', - * /' },
      { name: 'hour',    label: 'Hour',         range: '0–23',    special: ', - * /' },
      { name: 'dom',     label: 'Day (month)',  range: '1–31',    special: ', - * / L W' },
      { name: 'month',   label: 'Month',        range: '1–12',    special: ', - * /' },
      { name: 'dow',     label: 'Day (week)',   range: '0–7',     special: ', - * / L #' },
    ],
  },
  {
    id: 'quartz',
    label: 'Quartz',
    description: '6-field format used by Quartz Scheduler, Spring @Scheduled, AWS Lambda',
    fieldCount: 6,
    placeholder: '0 * * * * *',
    example: '0 0 9 * * MON-FRI',
    fields: [
      { name: 'second',  label: 'Second',      range: '0–59',    special: ', - * /' },
      { name: 'minute',  label: 'Minute',      range: '0–59',    special: ', - * /' },
      { name: 'hour',    label: 'Hour',         range: '0–23',    special: ', - * /' },
      { name: 'dom',     label: 'Day (month)',  range: '1–31',    special: ', - * / L W ?' },
      { name: 'month',   label: 'Month',        range: '1–12',    special: ', - * /' },
      { name: 'dow',     label: 'Day (week)',   range: '1–7',     special: ', - * / L # ?' },
    ],
  },
  {
    id: 'github',
    label: 'GitHub Actions',
    description: 'Standard Unix 5-field cron used in GitHub Actions workflow schedules',
    fieldCount: 5,
    placeholder: '0 0 * * *',
    example: '30 5 * * 1,3,5',
    fields: [
      { name: 'minute',  label: 'Minute',      range: '0–59',    special: ', - * /' },
      { name: 'hour',    label: 'Hour',         range: '0–23',    special: ', - * /' },
      { name: 'dom',     label: 'Day (month)',  range: '1–31',    special: ', - * /' },
      { name: 'month',   label: 'Month',        range: '1–12',    special: ', - * /' },
      { name: 'dow',     label: 'Day (week)',   range: '0–6',     special: ', - * /' },
    ],
  },
  {
    id: 'aws',
    label: 'AWS EventBridge',
    description: '6-field format for AWS EventBridge (CloudWatch Events) rules',
    fieldCount: 6,
    placeholder: '0 12 * * ? *',
    example: '0 10 ? * MON-FRI *',
    fields: [
      { name: 'minute',  label: 'Minute',      range: '0–59',    special: ', - * /' },
      { name: 'hour',    label: 'Hour',         range: '0–23',    special: ', - * /' },
      { name: 'dom',     label: 'Day (month)',  range: '1–31',    special: ', - * / L W ?' },
      { name: 'month',   label: 'Month',        range: '1–12',    special: ', - * /' },
      { name: 'dow',     label: 'Day (week)',   range: '1–7',     special: ', - * / L # ?' },
      { name: 'year',    label: 'Year',         range: '1970–2199', special: ', - * /' },
    ],
  },
];

export const CRON_PRESETS: CronPreset[] = [
  { label: 'Every minute',              expression: '* * * * *',     format: 'unix',   description: 'Runs every minute' },
  { label: 'Every 5 minutes',           expression: '*/5 * * * *',   format: 'unix',   description: 'Runs every 5 minutes' },
  { label: 'Every 15 minutes',          expression: '*/15 * * * *',  format: 'unix',   description: 'Runs every 15 minutes' },
  { label: 'Every 30 minutes',          expression: '*/30 * * * *',  format: 'unix',   description: 'Runs every 30 minutes' },
  { label: 'Every hour',                expression: '0 * * * *',     format: 'unix',   description: 'Runs at the start of every hour' },
  { label: 'Every 6 hours',             expression: '0 */6 * * *',   format: 'unix',   description: 'Runs at 00:00, 06:00, 12:00, 18:00' },
  { label: 'Daily at midnight',         expression: '0 0 * * *',     format: 'unix',   description: 'Runs once a day at midnight' },
  { label: 'Daily at noon',             expression: '0 12 * * *',    format: 'unix',   description: 'Runs once a day at 12:00 PM' },
  { label: 'Daily at 9 AM',             expression: '0 9 * * *',     format: 'unix',   description: 'Runs once a day at 9:00 AM' },
  { label: 'Weekdays at 9 AM',          expression: '0 9 * * 1-5',   format: 'unix',   description: 'Runs Mon–Fri at 9:00 AM' },
  { label: 'Weekends at noon',          expression: '0 12 * * 6,0',  format: 'unix',   description: 'Runs Sat and Sun at 12:00 PM' },
  { label: 'Every Monday at 8 AM',      expression: '0 8 * * 1',     format: 'unix',   description: 'Runs every Monday at 8:00 AM' },
  { label: 'Weekly on Sunday',          expression: '0 0 * * 0',     format: 'unix',   description: 'Runs every Sunday at midnight' },
  { label: 'First of every month',      expression: '0 0 1 * *',     format: 'unix',   description: 'Runs at midnight on the 1st of each month' },
  { label: 'Last day of month (ish)',   expression: '0 0 28-31 * *', format: 'unix',   description: 'Runs near end of month (adjust as needed)' },
  { label: 'Every quarter',             expression: '0 0 1 1,4,7,10 *', format: 'unix', description: 'Runs on the 1st of Jan, Apr, Jul, Oct' },
  { label: 'Twice daily',               expression: '0 8,20 * * *',  format: 'unix',   description: 'Runs at 8 AM and 8 PM every day' },
  { label: 'Yearly (Jan 1st)',          expression: '0 0 1 1 *',     format: 'unix',   description: 'Runs at midnight on January 1st' },
  { label: 'GitHub Actions: nightly',   expression: '0 2 * * *',     format: 'github', description: 'CI nightly build at 2 AM UTC' },
  { label: 'AWS: business hours',       expression: '0 8-18 ? * MON-FRI *', format: 'aws', description: 'Every hour during business hours, weekdays' },
];

export const TIMEZONES = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Asia/Kolkata',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Australia/Sydney',
];
